#!/bin/bash
pushd @@REPODIR@@ > /dev/null

if [ "@@NEWKEYWORD@@" = "@@ARCH@@" ]; then
	DESCR="Stabilize @@ARCH@@"
else
	DESCR="Keyword @@ARCH@@"
fi

if [ -n "@@BUG@@" ]; then
	DESCR="${DESCR}, #@@BUG@@"
fi
