#!/bin/bash
# Reverse dependency testing for @@JOB@@

trap "echo 'signal captured, exiting the entire script...'; exit" SIGHUP SIGINT SIGTERM 

export TATT_TEST_TYPE="rdep"
export TATT_REPORTFILE="@@REPORTFILE@@"
export TATT_BUILDLOGDIR="@@BUILDLOGDIR@@"
export TATT_EMERGEOPTS="@@EMERGEOPTS@@"

source "@@TEMPLATEDIR@@tatt_functions.sh"

test_ret=0

export USE

echo -e "revdep tests started on $(date)\n" >> @@REPORTFILE@@
