#!/usr/bin/env python
# Copyright 2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

import portage.versions
import requests
import sys
from tatt.tattConfig import tattConfig as tattConfig


def main():
	tattconfig = tattConfig()
	session = requests.Session()
	session.params.update({'Bugzilla_api_key': tattconfig['bugzilla-key']})

	bug_url = tattconfig['bugzilla-url']
	bug_id = str(@@BUG@@)

	params = {'id': bug_id}
	response = session.get(tattconfig['bugzilla-url'] + '/rest/bug', params=params).json()

	if 'message' in response:
		print(response['message'])
		sys.exit(1)

	response = response['bugs'][0]

	has_my_arch = False
	has_other_arches = False
	for cc in response['cc']:
		body, domain = cc.split('@', 1)
		if domain == 'gentoo.org':
			if body == '@@ARCH@@':
				has_my_arch = True
			elif body in portage.archlist:
				has_other_arches = True

	# We don't close bugs which still have other arches for obvious reasons,
	# and security bugs because stabilization is not the last step for them.
	if '@@NEWKEYWORD@@' == '@@ARCH@@':
		comment = "@@ARCH@@ stable"
	else:
		comment = "@@ARCH@@ keyworded"
	params['cc'] = {}
	if has_my_arch:
		params['cc']['remove'] = ['@@ARCH@@@gentoo.org']
	params['comment'] = {}
	if has_other_arches or 'Security' in response['product']:
		params['comment']['body'] = comment
	else:
		params['comment']['body'] = comment + ', closing'
		params['status'] = 'RESOLVED'
		params['resolution'] = 'FIXED'

	session.put(tattconfig['bugzilla-url'] + '/rest/bug/' + bug_id, json=params)

if __name__ == '__main__':
	main()
